spring:
  batch:
    job:
      names: ${job.name:NONE}
  db1:
    datasource:
      jdbc-url: jdbc:mysql://192.168.100.100:3306/r103?serverTimezone=Asia/Seoul
      username: user01
      password: user01
  db2:
    datasource:
      jdbc-url: jdbc:mysql://192.168.100.100:23306/r103?serverTimezone=Asia/Seoul
      username: user01
      password: user01

